### ISSUE TITLE
File generated by an older version of protoc

### ISSUE THREAD

**Issue by TELunus** [prash-wghats/Electron-VSCode-Atom-For-FreeBSD#19]
When I run `build_atom.sh` I get an error saying:
```In file included from ../../net/quic/core/congestion_control/tcp_cubic_sender_bytes.cc:12:
gen/net/quic/core/proto/cached_network_parameters.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
gen/net/quic/core/proto/cached_network_parameters.pb.h:18:2: error: incompatible with your Protocol Buffer headers.  Please
#error incompatible with your Protocol Buffer headers.  Please
 ^
gen/net/quic/core/proto/cached_network_parameters.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
gen/net/quic/core/proto/cached_network_parameters.pb.h:66:1: error: too many arguments to function call, expected 0, have 1
&::google::protobuf::internal::GetEmptyStringAlreadyInited());
```
The error comes while running `script/build --no_shared_library -t x64` on line 30 of `build_atom.sh`

This is with the current master branch, trying to build on 11.2-RELEASE.  I had what I believe was the same error on 11.1-RELEASE, but I didn't log it so I can't confirm.

**Comment by TELunus** [comment]
I did some more digging and it looks like the offending lines are lines 16-20 of `atom/libchromiumcontent/src/out-x64/static_library/gen/net/quic/core/proto`:
```c++
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif
```
which is generated when line 29 of `build_atom` runs `script/update -t 'x64'`, particularly when line 223/224 of that script in turn runs 
```python
subprocess.call([gn, 'gen', os.path.relpath(output_dir, SRC_DIR), '--args=' + args],
                    cwd=SRC_DIR, env=env)
```
which for me resolves to running 
``` bash
atom/libchromiumcontent/src/out/Release/gn 'gen' 'out-x64/static_library' '--args=import("//chromiumcontent/args/static_library.gn") target_cpu="x64" is_clang=true  clang_use_chrome_plugins=false  enable_media_router=true  enable_nacl=false  enable_one_click_signin=true  enable_remoting=false  enable_webrtc=false  fieldtrial_testing_like_official_build=true  toolkit_views=true  use_allocator="none"  use_aura=true  use_cups=true  use_experimental_allocator_shim=false  treat_warnings_as_errors=false  use_sysroot=false  use_system_libjpeg=true  use_system_sqlite=false  use_alsa=false ffmpeg_branding="Chrome" proprietary_codecs=true enable_hevc_demuxing=true use_lld=true is_debug=false symbol_level=0 remove_webcore_debug_symbols=true use_gconf=true use_kerberos=true use_pulseaudio=true extra_cxxflags="-O2 -I/usr/local/include"'
```

Alas I still don't understand why this doesn't generate files that mach the defines used in the build.

**Comment by prash-wghats** [comment]
Most probably your build is pulling in system google protobuf library. Try building after removing the system google protobuf.

**Comment by TELunus** [comment]
Thanks for your help!

This computer's been powered down for a bit, but I just booted it back up and tried that, but it gave me the following error:

```
===>  chromium-56.0.2924.87_2 requires unknown xorg module (xproto).
*** Error code 1

Stop.
make: stopped in /files/fileroot/Projects/Freebsd-Atom/Test/atom/chromium
```

**Comment by prash-wghats** [comment]
Recent versions of ports `xproto` has been replaced with `xorgproto`
